### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by Maniues** [Sound-Linux-More/v2mdump#2]
PDMark is only a mark, not public domain dedication. So, use [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed) instead of PDMark and be sure that this software will be in public domain!

**Comment by zvezdochiot** [comment]
https://creativecommons.org/publicdomain/mark/1.0/

**Comment by Maniues** [comment]
>The work may not be free of known copyright restrictions in all jurisdictions. 
 
 Copied from PDMark.
 Public Domain Mark is only a MARK. So it's recommended to use it in some old photos, music etc. 
 For copyrighted materials, PDMark it's not recommended

**Comment by zvezdochiot** [comment]
Prove it!

**Comment by Maniues** [comment]
Please wait

**Comment by Maniues** [comment]
Creative Commons, creators of the PDMark, and a lot of licenses:
https://creativecommons.org/share-your-work/public-domain/pdm/
> Recommended Uses of the Public Domain Mark
The Public Domain Mark is recommended for works that are free of known copyright around the world. These will typically be very old works.  It is not recommended for use with works that are in the public domain in some jurisdictions if they also known to be restricted by copyright in others.

Wikipedia:
> The Public Domain Mark was developed by Creative Commons[1][2] and is only an indicator of the public domain status of a work -- it itself doesn't release a copyrighted work into the public domain like CC0. 
https://en.wikipedia.org/wiki/Public_Domain_Mark
> The work may not be free of known copyright restrictions in all jurisdictions.

From PDMark
What CC0 do?
CC0 grant a public license fallback:
> Public License Fallback. Should any part of the Waiver for any reason be judged legally invalid or ineffective under applicable law, then the Waiver shall be preserved to the maximum extent permitted taking into account Affirmer's express Statement of Purpose. In addition, to the extent the Waiver is so judged Affirmer hereby grants to each affected person a royalty-free, non transferable, non sublicensable, non exclusive, irrevocable and unconditional license to exercise Affirmer's Copyright and Related Rights in the Work (i) in all territories worldwide, (ii) for the maximum duration provided by applicable law or treaty (including future time extensions), (iii) in any current or future medium and for any number of copies, and (iv) for any purpose whatsoever, including without limitation commercial, advertising or promotional purposes (the "License"). The License shall be deemed effective as of the date CC0 was applied by Affirmer to the Work. Should any part of the License for any reason be judged legally invalid or ineffective under applicable law, such partial invalidity or ineffectiveness shall not invalidate the remainder of the License, and in such case Affirmer hereby affirms that he or she will not (i) exercise any of his or her remaining Copyright and Related Rights in the Work or (ii) assert any associated claims and causes of action with respect to the Work, in either case contrary to Affirmer's express Statement of Purpose.

https://creativecommons.org/publicdomain/zero/1.0/legalcode
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by Maniues** [comment]
Additionally, CC0 clearly means that you are waiving any copyrights:
>2. Waiver. To the greatest extent permitted by, but not in contravention of, applicable law, Affirmer hereby overtly, fully, permanently, irrevocably and unconditionally waives, abandons, and surrenders all of Affirmer's Copyright and Related Rights and associated claims and causes of action, whether now known or unknown (including existing as well as future claims and causes of action), in the Work (i) in all territories worldwide, (ii) for the maximum duration provided by applicable law or treaty (including future time extensions), (iii) in any current or future medium and for any number of copies, and (iv) for any purpose whatsoever, including without limitation commercial, advertising or promotional purposes (the "Waiver"). Affirmer makes the Waiver for the benefit of each member of the public at large and to the detriment of Affirmer's heirs and successors, fully intending that such Waiver shall not be subject to revocation, rescission, cancellation, termination, or any other legal or equitable action to disrupt the quiet enjoyment of the Work by the public as contemplated by Affirmer's express Statement of Purpose.

**Comment by Maniues** [comment]
Creative Commons place theirs license texts under CC0, not PDMark

**Comment by zvezdochiot** [comment]
@Maniues say:
>Additionally, CC0 clearly means that you are waiving any copyrights

Right! Everything suits me!
